### PR TITLE
CBOR tag numbers must be TN-derived

### PR DESCRIPTION
**Pull request by thomas-fossati**

### CODE REVIEW

**Comment by nedmsmith** [comment]
We didn't discuss the rationale for why it makes sense for a Content-ID that is from the "standards" range is mapped to a CBOR tag from the FCFS range. This seems wrong. An equivalent ("alias"?) value from one registry should have the same semantics in terms of standard/FCFS/experiential when mapped to another registry (for the same content but with different formatting). 

A mapping semantic that doesn't violate typing expectations would preserve the standards/FCFS/experimental designation across the various forms.

**Comment by thomas-fossati** [comment]
> We didn't discuss the rationale for why it makes sense for a Content-ID that is from the "standards" range is mapped to a CBOR tag from the FCFS range.

I don't understand why this is relavant.  Although, technically within the FCFS range, the TN space [1668546817, 1668612095] is a carve-out that can't be assigned anymore.  I think IANA missed (or wasn't properly instructed) to update the registry header to reflect that.

It should say:

Range | Registration Procedures
-- | --
0-23 | Standards Action
24-32767 | Specification Required
32768-1668546816 | First Come First Served
1668546817, 1668612095 | Reserved (TN-derived)
1668612096-18446744073709551615 | First Come First Served

**Comment by nedmsmith** [comment]
Does it make sense to include the IANA correction in this draft?

**Comment by cabo** [comment]
What 9277 Section 4.3 says is this:

> 4.3. CBOR Tags for CoAP Content-Format Numbers
> IANA allocated the tag numbers 1668546817 (0x63740101) to 1668612095 (0x6374ffff) as follows:

Clearly, these are *allocated* (assigned), not reserved.
True, you can’t *use* the allocation for a specific tag number before there is an assignment for the corresponding ct number, but that doesn’t make the tag numbers in any way less allocated (assigned).

I have no idea how these two assignment ranges (tag numbers 1668546817 (0x63740101) to 1668612095 (0x6374ffff), and content-format numbers 0..65024) are getting confused; they are linked by a formula, not by one registration policy somehow seeping over into the other space.

**Comment by thomas-fossati** [comment]
> What 9277 Section 4.3 says is this:
> 
> > 4.3. CBOR Tags for CoAP Content-Format Numbers
> > IANA allocated the tag numbers 1668546817 (0x63740101) to 1668612095 (0x6374ffff) as follows:
> 
> Clearly, these are _allocated_ (assigned), not reserved. True, you can’t _use_ the allocation for a specific tag number before there is an assignment for the corresponding ct number, but that doesn’t make the tag numbers in any way less allocated (assigned).

Thank you for the clarification. I have some reservations (pun intended) about the use of terms—the semantics of allocation versus assignment—but I will refrain from going down that specific rabbit hole 😅

> I have no idea how these two assignment ranges (tag numbers 1668546817 (0x63740101) to 1668612095 (0x6374ffff), and content-format numbers 0..65024) are getting confused; they are linked by a formula, not by one registration policy somehow seeping over into the other space.

👍

**Review by henkbirkholz — APPROVED** [review]
I am okay with TN tags "used as CMW" (:roll_eyes:) only in this context.

**Comment by nedmsmith** [comment]
> they are linked by a formula, not by one registration policy somehow seeping over into the other space.

I'm looking at it from the perspective of how it could be abused. Maybe others are looking at it from the perspective of how it is supposed to be used. Many of IANA registries have differential vetting requirements. If someone gets an assignment from the CF.Id using weaker vetting (say experimental), generates a TN tag then uses the tag in a standard somewhere else. The new standard essentially becomes the new vetting entity. Users of the TN tag likely would not be aware of the vetting differential (maybe it doesn't matter either?), but if it did, the only way to know which vetting was applied is by reversing the TN algorithm, find the ct value, and review the CF registry. It seems unlikely parsers would do this just to check for vetting process differentials. Since the CBOR tags registry has already allocated TN tags, there's no risk that the CBOR tags registrar will assign the tag to something else. So, it's safe for new standard to use it. At the end of the day, IANA isn't providing vetting for a class of CBOR tags (neither the CF or the CBOR tags registrars). They are only ensuring uniqueness. The real vetting is applied by the organization that is using the TN tag. If the goal is to centralize vetting to the CF registrar, this seems to only work if: (1) there is no differential in CF vetting rules. Or (2), if the ct values is somehow encoded with the TN CBOR tag: `CBOR_Tag = { ct, tn-cbor-tag }` and parsers check that the ct vetting is appropriate for the intended use. Or (3), the TN assigned values are partitioned according to the CF vetting that was applied. Then a range check of TN number removes the need for including ct in the CBOR_Tag. However, a different TN function would be needed.

If we conclude that none of this matters, then we are saying the vetting procedures aren't actually adding value. IANA's value is simply to guarantee unique names / numbers are assigned.

**Comment by thomas-fossati** [comment]
> > they are linked by a formula, not by one registration policy somehow seeping over into the other space.
> 
> I'm looking at it from the perspective of how it could be abused. Maybe others are looking at it from the perspective of how it is supposed to be used. Many of IANA registries have differential vetting requirements. If someone gets an assignment from the CF.Id using weaker vetting (say experimental), generates a TN tag then uses the tag in a standard somewhere else. The new standard essentially becomes the new vetting entity. Users of the TN tag likely would not be aware of the vetting differential (maybe it doesn't matter either?), but if it did, the only way to know which vetting was applied is by reversing the TN algorithm, find the ct value, and review the CF registry. It seems unlikely parsers would do this just to check for vetting process differentials. Since the CBOR tags registry has already allocated TN tags, there's no risk that the CBOR tags registrar will assign the tag to something else. So, it's safe for new standard to use it. At the end of the day, IANA isn't providing vetting for a class of CBOR tags (neither the CF or the CBOR tags registrars). They are only ensuring uniqueness. The real vetting is applied by the organization that is using the TN tag. If the goal is to centralize vetting to the CF registrar, this seems to only work if: (1) there is no differential in CF vetting rules. Or (2), if the ct values is somehow encoded with the TN CBOR tag: `CBOR_Tag = { ct, tn-cbor-tag }` and parsers check that the ct vetting is appropriate for the intended use. Or (3), the TN assigned values are partitioned according to the CF vetting that was applied. Then a range check of TN number removes the need for including ct in the CBOR_Tag. However, a different TN function would be needed.
> 
> If we conclude that none of this matters, then we are saying the vetting procedures aren't actually adding value. IANA's value is simply to guarantee unique names / numbers are assigned.

There are loopholes in the C-F registration process that allow accidental abuse.  We discovered it first-hand :-)

That's simply a bug that must be fixed, and [we are going to fix it](https://thomas-fossati.github.io/draft-cf-reg-update/draft-fossati-core-cf-reg-update.html).

Once the registration procedure is tightened, as it should be, we're going to have a single entry point at which all the vetting is applied consistently and correctly, which is sensibly better than having multiple separate vetting places.

**Review by nedmsmith — APPROVED** [review]

**Pull request merged**
